resolver: lts-8.9

packages:
- '.'
- dep1
- dep2
- location:
    git: https://github.com/jmitchell/haskell-dummy-project1
    commit: 7e7d91d86ba0f86633ab37279c013879ade09e32
  extra-dep: true

extra-deps: []

flags: {}

extra-package-dbs: []
